### ISSUE TITLE
Fingerprinting amd-start.js and amd-config.js for CDN support

### ISSUE THREAD

**Issue by dbouwman** [Esri/ember-cli-amd#12]
Since we deploy the build assets to a cloud-fronted S3 bucket, we need `amd-start.js` and `amd-config.js` files to be fingerprinted to effectively bust the caching that is inherent in CDNs.

Another option that would avoid this would be to inline these scripts in the page vs writing out files.

Either way, right now we need to manually delete these files from S3 before we do a deploy, which could incur app downtime.

**Comment by dbouwman** [comment]
@odoe @ffaubry Thoughts on this? Personally, I'd lean towards inlining vs fingerprinting, but you may have/know-of reasons why having the amd-start and amd-config as external scripts.

Right now this really hampers our deploy process - and given that we deploy to devext & qa on virtually every PR... :)

If we go the inlining route, I can likely take a stab at it - I've not tackled fingerprinting files before but I'm sure it's not that rough.

**Comment by mjuniper** [comment]
:+1: for inlining.

**Comment by ffaubry** [comment]
@dbouwman If I understand correctly your proposal you would take the config script and push it inside the index.html? Ditto for the start script?
Another route is to fingerprint the config script and the start script. We can do that in the addon.

**Comment by odoe** [comment]
@dbouwman It would be awesome if you PR an option to inline the script. That would be a cool option!

**Comment by dbouwman** [comment]
@ffaubry either one would work, but I'm inclined to inline it because that saves 2 xhrs during the app boot, which - while not much - does have an impact.

I'll look at making inlining the scripts an option this evening.

**Comment by ffaubry** [comment]
@dbouwman looking forward for the PR :)

**Comment by odoe** [comment]
Fixed in #16
