### ISSUE TITLE
Test-loader is broken

### ISSUE THREAD

**Issue by ffaubry** [Esri/ember-cli-amd#21]
The replacement of 'require' by 'equireray' in the test-loader when using 'ember test' brake the code.
Test-loader is wrapping the require form the loader. The 'require' in these lines of code should have also been replaced by 'equireray':
```
   TestLoader.prototype.unsee = function(moduleName) {
     if (typeof require.unsee === 'function') {
       require.unsee(moduleName);
     } else if (!this._didLogMissingUnsee) {
      this._didLogMissingUnsee = true;
      if (typeof console !== 'undefined') {
        console.warn('unable to require.unsee, please upgrade loader.js to >= v3.3.0');
      }
     }
    };
```

I think the best way to fix this is to pig latin all the 'require' in the test-loader.

**Comment by ffaubry** [comment]
mentioning @jrowlingson

**Comment by odoe** [comment]
fixed in https://github.com/Esri/ember-cli-amd/pull/22
