### ISSUE TITLE
Broken in ember 2.4.1

### ISSUE THREAD

**Issue by mjuniper** [Esri/ember-cli-amd#24]
In ember 2.4.1, the addon works, however, the tests break.

When I do `ember test -s`, I see:

```
Global error: Error: Could not find module `ember-cli/test-loader` imported from `(equireray)` at http://localhost:7357/assets/vendor.js, line 173

Global error: Error: Could not find module `ember-qunit` imported from `ember-test-app-2/tests/test-helper` at http://localhost:7357/assets/vendor.js, line 17
3

Error: Could not find module `ember-cli/test-loader` imported from `(equireray)` at http://localhost:7357/assets/vendor.js, line 173
Error: Could not find module `ember-qunit` imported from `ember-test-app-2/tests/test-helper` at http://localhost:7357/assets/vendor.js, line 173
```

**Comment by jrowlingson** [comment]
@mjuniper temporary workaround: 
```zsh 
bower install jquery#2.1.4 && ember t -s
```

**Comment by odoe** [comment]
If the jQuery update worked for you @mjuniper could you verify and close the issue? Thanks!

**Comment by mjuniper** [comment]
Well, it did work but I don't understand why. Also, at ember 2.3+ (I think) you are not supposed to need to have jquery in your bower.json at all.

**Comment by odoe** [comment]
Well, that is just weird. I'll test a little further on this one before closing it.

**Comment by jrowlingson** [comment]
> Also, at ember 2.3+ (I think) you are not supposed to need to have jquery in your bower.json at all.

This is correct.

> I'll test a little further on this one before closing it.

I would suggest keeping the issue open until a proper fix is in place.

**Comment by mjuniper** [comment]
> I would suggest keeping the issue open until a proper fix is in place.

I agree. Thanks @jrowlingson

**Comment by odoe** [comment]
This is really weird. Testing in Ember 2.4.3 and jQuery default install is 2.2.2, which breaks `testem` w/addon. Just going back to 2.1.4 does fix it, but I don't know why. Scripts are still loaded in same order, nothing jumps out.

I'll keep cracking away at it, thanks!

**Comment by nwhittaker** [comment]
I think I got to the bottom of this issue (at least for Backoffice). In short, I needed to reverse the order in which `assets/test-loader.js` and `assets/test-support.js` are referenced in `tests/index.html`. See [workforce-js#1294 (comment)](https://github.com/ArcGIS/workforce-js/pull/1294/files#r66730724) for a longer description of what I think was going on.

**Comment by nwhittaker** [comment]
I see that `ember-cli` loads `test-loader` after `test-support` by default. I wonder if a better fix for this issue is to load the script resources in `tests/index.html` in parallel rather than serially (unless there's a reason to do it this way?) -- and use Require's shim config to indicate the order in which to load `test-support` and `test-loader`?

**Comment by JaronAndre** [comment]
FYI for anyone look at this issue now: 
This issues doesn't appear to exist with the latest version of Ember (2.10 is what I'm trying with). Ember has updated its QUint test suite to version 2 since this bug was filed so that may have removed the issue.
