### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by tanya-tee** [Esri/ember-cli-amd#25]
ReferenceError: require is not defined

**Comment by odoe** [comment]
Do you have a version of Firefox and OS you see this error so I can try and reproduce?

Thanks!

**Comment by tanya-tee** [comment]
Dear Rene,
After trying to make it work it came down to a weird issue with Esri and zScaler (the software my company is using).
Would you like me to delete the issue I created from github? I'm relatively new to it. Please let me know.
Great add-on.
Thank you,-Tanya 

    On Tuesday, April 12, 2016 3:31 PM, Rene Rubalcava <notifications@github.com> wrote:
 

 Do you have a version of Firefox and OS you see this error so I can try and reproduce?Thanks!—
