### ISSUE TITLE
Decorators support

### ISSUE THREAD

**Issue by jrowlingson** [Esri/ember-cli-amd#26]
Unable to use [ember-computed-decorators](https://github.com/rwjblue/ember-computed-decorators) as esprima currently [does not support](https://github.com/jquery/esprima/issues/1387) decorators (stage 1).

**Comment by ggayowsky** [comment]
With Octane coming, and Ember going to be recommending ES class syntax (even though decorators will be in Stage 2), this issue going to become a blocker for people wishing to use this add-on and  other features (e.g. glimmer components)

**Comment by ffaubry** [comment]
@ggayowsky We are using ES native class in Operations Dashboard with ember-decorators.
It's working well.

**Comment by ggayowsky** [comment]
@ffaubry On the latest version (1.2.4 at the time of writing this)? I guess this issue should be closed then?

**Comment by ffaubry** [comment]
@ggayowsky Correct in the recent releases, we fixed a series of issues related to ember-decorators and ember-auto-import

Closing.
