### ISSUE TITLE
Not playing nicely with Ember Inspector

### ISSUE THREAD

**Issue by derekwsgray** [Esri/ember-cli-amd#33]
Using the Ember Inspector browser extension, I'm getting odd-ball requests on the first two loads (i.e. it works the 3rd time the page is loaded) such as:

vendor.js:180 Uncaught Error: Could not find module `ember-debug/adapters/chrome` imported from `(equireray)`missingModule @ vendor.js:180findModule @ vendor.js:194requireModule @ vendor.js:184sendVersionMiss @ VM155:7814(anonymous function) @ VM155:7685triggerOnce @ VM155:7733completed @ VM155:7755
init.js:30 GET **http://js.arcgis.com/3.15/ember-debug/addons/ember-new-computed/utils/can-use-new-syntax.js** r.injectUrl @ init.js:30pa @ init.js:27a @ init.js:5(anonymous function) @ init.js:14ia @ init.js:23ma @ init.js:14Ia @ init.js:31(anonymous function) @ VM155:488(anonymous function) @ VM155:7891
init.js:31 Error: scriptError(…)(anonymous function) @ init.js:31(anonymous function) @ init.js:9a @ init.js:5r.signal @ init.js:9(anonymous function) @ init.js:30
init.js:31 src: dojoLoader
init.js:31 info: ["**http://js.arcgis.com/3.15/ember-debug/addons/ember-new-computed/utils/can-use-new-syntax.js**", Event]

Ember-cli 2.5.1
ember-cli-amd 0.4.7

**Comment by ffaubry** [comment]
Since we are transforming the app into amd modules and changing the ember define/require function name to not conflict with AMD, we will never play nicely with Ember Inspector.
Known limit.
