### ISSUE TITLE
Does not work with ember-auto-import

### ISSUE THREAD

**Issue by ggayowsky** [Esri/ember-cli-amd#39]
Having this add-on + ember-auto-import causes issues.

**Comment by tomwayson** [comment]
Can you elaborate on said issues? Can you provide any build and/or runtime errors?

**Comment by odoe** [comment]
Unfortunately, it looks like ember-auto-import use webpack to create bundles during the build process.
https://github.com/ef4/ember-auto-import/blob/master/ts/bundler.ts#L69-L75

This workflow is not going to work with this plugin as we do an AMD build of files during the build process.

**Comment by ffaubry** [comment]
@ggayowsky It must be fixed with the latest version (>= 1.2.4)
