### ISSUE TITLE
Add option to have injected javascript non-inline

### ISSUE THREAD

**Issue by ggayowsky** [Esri/ember-cli-amd#45]
Prior to version 2, this addon had the ability add the injected javascript in a hosted src file (amd-start & amd-config.js) instead of always putting the code inline.

Due to security concerns (such as a CSP that does not allow inline scripts) this functionality should be re-implemented.

**Comment by ggayowsky** [comment]
I would like to tackle this, however, I am wondering how you develop this addon as the docs are quite sparse on how to develop an addon like this (mostly just using the addon hooks and methods). If there is someone I can talk to that would be great.

**Comment by ffaubry** [comment]
With version 3.0.0, everything is not inlined.
Closing.
