### ISSUE TITLE
extract require/define replacement into own package

### ISSUE THREAD

**Issue by tomwayson** [Esri/ember-cli-amd#48]
I'd like to extract the require/define replacement code from this addon into it's own package so that ember-esri-loader can share the logic (or even better so that I can get rid of ember-esri-loader all together and just pull in esri-loader via ember-auto-import).

I read through `index.js`, and I don't fully grok everything that's going on, but I'm guessing that would involve moving at least `RequireFilter` and `replaceRequireAndDefine()` into a new package like `broccoli-require-filter`. Then this addon and others would do:

`const { RequireFilter, replaceRequireAndDefine } = require('broccoli-require-filter');`

Does that sound like it would work? Are there other pieces that I'm missing that would also need to be extracted?

Would you be interested in that if I were to create the new package, get it working in ember-esr-loader, and then PR an update here?

**Comment by tomwayson** [comment]
Looks like I'd move the `identifiers` and `literals` too.

**Comment by ffaubry** [comment]
@tomwayson I have re-structured the code into module following an idea from @ggayowsky.
It should help you reuse some parts.
Propose a PR if you need further modifications.

**Comment by tomwayson** [comment]
Thanks @ffaubry!

Looks like somebody (Robert Jackson no less) has beaten us to the punch:

https://github.com/rwjblue/broccoli-derequire

Also, have you seen this:

https://github.com/richardaiko/ember-derequire

Sadly some of the [open issues](https://github.com/richardaiko/ember-derequire/issues) there make me suspect that those are not functionally on par w/ the level of replacement that is supported by this addon or even ember-esri-loader (which supports lazy engines).

One way or another I'd really like to centralize the find and replace logic and make it consistent.

**Comment by ffaubry** [comment]
@tomwayson 
To beat someone to the punch you need to deliver before the others... This is delivering after ember-ci-amd has been out for 3 years and solved the issue correctly!
And yes, it's probably not covering all the issues.

I remind you, that ember-cli-amd supports engines and auto import.
We have reworked the code to make the main parts as module. Up to you to get this in ember-esri-loader...

With a little effort the ember-cli-amd could also lazy loads AMD modules. Just have to implement a smart service...

**Comment by tomwayson** [comment]
Specifically I meant beat to the punch on the idea of moving things into a broccoli plugin.

**Comment by ffaubry** [comment]
That's what we do: https://github.com/Esri/ember-cli-amd/blob/master/lib/replace-require-and-define-filter.js
This is a plugin!
We could have released it as a plugin.
We are a subclass of `const Filter = require('broccoli-filter');`
broccoli-filter is a subclass of `require('broccoli-plugin');`

**Comment by ffaubry** [comment]
Closing
