### ISSUE TITLE
Demo source code

### ISSUE THREAD

**Issue by OyoKooN** [Esri/ember-cli-amd#5]
Hello,

Is it possible to have access to the source code of the demo app?
I can't manage to get it to work (using Ember CLI 1.13.8).

Thanks

**Comment by odoe** [comment]
Sorry about that, here is the source code used for the demo.
https://github.com/odoe/ember-esrijs

**Comment by OyoKooN** [comment]
Thanks! :)

--
Nathan Le Ray (@OyoKooN[1])
 
 
On Wed, Sep 30, 2015, at 08:05 PM, Rene Rubalcava wrote:
> Sorry about that, here is the source code used for the demo.
> https://github.com/odoe/ember-esrijs


> —
> Reply to this email directly or view it on GitHub[2]. 


>  


Links:

  1. https://twitter.com/OyoKooN
  2. https://github.com/Esri/ember-cli-amd/issues/5#issuecomment-144493253
