### ISSUE TITLE
Project will not build when you change the default root

### ISSUE THREAD

**Issue by Mciocca** [Esri/ember-cli-amd#58]
If you change the default root from '/' to something like '/blog', the build errors out with an error similiar to:
```
Build Error (ConvertToAMD)

ENOENT: no such file or directory, open '/var/folders/bz/4mcxsd4x0zx8_brqzjpld6dc0000gn/T/broccoli-46016cGA7TN0S72TJ/out-255-convert_to_amd/blog/assets/amd-loading.js'

```
You can see that ```/blog``` has been added to the path where ember-cli is looking for the ```amd-loading.js```

A put together a quick demo app here that won't build due to this issue: 
https://github.com/Mciocca/arcgis-bug

This is only an issue when the rootUrl config is changed in `config/environment.js`

**Comment by ffaubry** [comment]
Fixed in https://github.com/Esri/ember-cli-amd/releases/tag/3.2.1
