### ISSUE TITLE
undefinedModule error from arcgis js library during tests

### ISSUE THREAD

**Issue by Mciocca** [Esri/ember-cli-amd#59]
I am getting an undefinedModule error when running tests in the browser on chrome (visiting /tests) after installing this plugin. The error is being thrown from inside of the arcgis js file. 

```
Uncaught Error: undefinedModule
    at p (:formatted:26)
    at ba (:formatted:228)
    at v (:formatted:33)
    at test-support-suffix.js:7
```

Being thrown from around here if this helpful:
```
// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.16/esri/copyright.txt for details.
//>>built
(function(e, b) {
    var a, m = function() {
        return "undefined" !== typeof q && "function" !== typeof q ? q : "undefined" !== typeof window ? window : "undefined" !== typeof self ? self : this
    }(), l = function() {}, k = function(a) {
        for (var c in a)
            return 0;
        return 1
    }, g = {}.toString, f = function(a) {
        return "[object Function]" == g.call(a)
    }, c = function(a) {
        return "[object String]" == g.call(a)
    }, d = function(a) {
        return "[object Array]" == g.call(a)
    }, h = function(a, c) {
        if (a)
            for (var d = 0; d < a.length; )
                c(a[d++])
    }, n = function(a, c) {
        for (var d in c)
            a[d] = c[d];
        return a
    }, p = function(a, c) {
      **// error happens here**
        return n(Error(a), {
            src: "dojoLoader",
            info: c
        })
```

**Comment by ffaubry** [comment]
@Mciocca  Please create a reproducible repository with steps. Thx.

**Comment by Mciocca** [comment]
@ffaubry 
You can use the same repository I made for the other bug:
https://github.com/Mciocca/arcgis-bug

If you attempt to visit ```localhost:4200/blog/tests```  it fails to load the page:
![Screen Shot 2020-11-17 at 4 38 58 PM](https://user-images.githubusercontent.com/3195676/99453846-8fd1fe00-28f3-11eb-8acf-0175ba26b19c.png)

After remove the library it loads as expected:
![Screen Shot 2020-11-17 at 4 36 30 PM](https://user-images.githubusercontent.com/3195676/99453619-35d13880-28f3-11eb-9b8a-2189b8f1f279.png)

Let me know if you need any more details from me.

**Comment by ffaubry** [comment]
Fixed by https://github.com/Esri/ember-cli-amd/releases/tag/3.2.2
